name: flutter_shop
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^2.0.7  
  flutter_swiper : ^1.1.6
  flutter_screenutil: ^0.5.3
  url_launcher: ^5.0.1
  flutter_easyrefresh: ^2.0.3
  provide: ^1.0.2
  flutter_spinkit: ^4.0.0
  fluttertoast: ^3.1.0
  fluro: ^1.5.1
  shared_preferences: ^0.5.3+4
  flutter_html: ^0.11.0
  intl: ^0.15.6
  amap_base: ^0.3.5
  jpush_flutter: ^0.1.0
  qr_flutter: ^3.0.1
  barcode_scan: ^1.0.0
  flutter_webview_plugin: ^0.3.8
  image_picker: ^0.6.1+8
  flustars: ^0.2.6+1
  city_pickers: ^0.1.28
  # path_provider: ^1.4.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/noCart.png
    - assets/images/yanxuan.png
    - assets/images/wechat.png
    - assets/images/qqchat.png
    - assets/images/weibo.png
    - assets/images/membg.png
    - assets/images/avatar.png
    - assets/images/noInfo.png
    - assets/images/qr.png
    - assets/images/01.png
    - assets/images/02.png
    - assets/images/03.png
    - assets/images/04.png
    - assets/images/05.png 
    - assets/images/06.png
    - assets/images/07.png
    - assets/images/08.png
    - assets/images/09.png
    - assets/images/10.png
    - assets/images/11.png
    - assets/images/12.png
    - assets/images/bg.png
    - assets/images/scan.png
    - assets/images/splash.jpeg
  # fonts:
  #       - family: MaterialIcons
  #         fonts:
  #           - asset: fonts/MaterialIcons.ttf
    # - family: MaterialIcons
    # fonts:
    #   - asset: assets/fonts/MaterialIcons.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
